### PR TITLE
internal/ui: use fallback mechanism for row icons

### LINKED ISSUE #227: Some icons not working on KDE
Image

It looks like some icons are missing, is there a missing Adwaita/Gnome dependency in the Flatpak which might not be obvious when running on a Gnome machine?

Also, just as a bit of feedback on this change: I love this change conceptually, but it's not quite clear to me what all these icons mean. The two blanked names are laptops and seem like they should be the same if they weren't missing. Most of the lock icons are services from my Kubernetes cluster, except the one selected one which is a phone. All of these are devices I have access to though, so a locked shield feels like a strange icon choice.

### LINKED ISSUE #232: [Improvment] Connection Icon Color
The new UI really looks great, and I like the new icons. However, one thing I really miss is the red and green to indicate if a particular device is currently connected to the tailnet or not. Is there any chance we can bring that back in some way? It is really nice to be able to see at a glance which ones are available or not.

Thank you.

P.S. Thank you for your hard work. The number of notifications I get daily from this project can sometimes be a little overwhelming, but it shows just how active you are. Great work. It is hard to believe sometimes that this is still considered beta software. for all intents and purposes, it works as well as I would expect for something considered a released utility.

### PR DESCRIPTION
**Pull request by DeedleFake**
Fixes #227. Closes #232.

### CODE REVIEW

File: internal/ui/peerpage.go [hunk 1]
```diff
@@ -303,19 +303,27 @@ func peerSubtitle(peer *ipnstate.PeerStatus) string {
 	return ""
 }
 
-func peerIcon(peer *ipnstate.PeerStatus) string {
+var (
+	peerIconExitNodeOffline = gio.NewThemedIconFromNames([]string{"network-vpn-acquiring-symbolic"})
```
Comment (mscharley) [inline internal/ui/peerpage.go:307]: Should this also include `"security-high-symbolic"` as a fallback too? This is the one which was actually missing.

Comment (DeedleFake) [reply internal/ui/peerpage.go:307]: Yep. I need to find a good way to come up with a list that'll both work and look nice across different desktops. I have KDE installed, so I just need to switch into that when I get a chance and experiment a bit.

For this particular one, I'm not sure what fallback makes more sense. The current icon is supposed to both indicate that it's being used as an exit node and that it's disconnected, and none of the fallbacks do both of those things at the same time well.

I think it being disconnected is more important for the icon to show, as it being an exit node is also indicated in the row's subtitle.

Comment (DeedleFake) [reply internal/ui/peerpage.go:323]: Unfortunately, it doesn't look like there's a way to fall back from a theme that isn't installed, just fallbacks for icons missing within a theme. I'm not sure what the behavior is if I try to force a theme that isn't installed at all. It might be dependent on the environment.

I'll experiment with forcing Adwaita and see if I can find icons in that theme that I like.

**Comment by DeedleFake** [comment]
Images for metainfo:
image
image
